### PR TITLE
Make CRS setup part of the ledger abstraction

### LINKED ISSUE #28: Abstract CRS setup
Currently, consumers of this abstract ledger interface must create a CRS themselves for generating CAP PLONK proofs. This is wrong; the CRS is going to be specific to a ledger in any realistic scenario, so `load_crs() -> UniversalParam` should be part of the `Ledger` interface.

### PR DESCRIPTION
**Pull request by jbearer**
Closes #28

### CODE REVIEW

File: src/cap.rs [hunk 1]
```diff
@@ -254,6 +266,10 @@ impl traits::Ledger for Ledger {
     fn record_root_history() -> usize {
         1
     }
+
+    fn crs() -> UniversalParam {
```
Comment (tri-joe) [inline src/cap.rs:270]: Why return `UniversalParam` rather than something like `&'static UniversalParam` or `Arc<UniversalParam>`?

**Review by tri-joe — CHANGES_REQUESTED** [review]
The type of `crs()` probably shouldn't require cloning it (since it's potentially quite large)

File: src/cap.rs (hunk 1 above)
Comment (jbearer) [reply src/cap.rs:270]: Good point. What about `<'a> Cow<'a, UniversalParam>`, which is I think the most compatible with the proving key setup APIs.

Comment (jbearer) [reply src/cap.rs:270]: Actually you know what I think `Arc` would be fine and simpler, I'll try that

Comment (jbearer) [reply src/cap.rs]: Nope, turns out `&'static` is the only one that really works with the rest of the codebase

File: Cargo.toml [hunk 2]
```diff
@@ -13,11 +13,9 @@ ark-serialize = { version = "0.3.0", features = ["derive"] }
 commit = { git = "https://github.com/EspressoSystems/commit.git", tag = "0.1.0" }
 funty = "=1.1.0"
 itertools = "0.10.1"
-jf-cap = { features=["std"], git = "https://github.com/EspressoSystems/cap.git" }
+jf-cap = { features=["std", "test_apis"], git = "https://github.com/EspressoSystems/cap.git" }
```
Comment (alxiong) [inline Cargo.toml:16]: I think the downstream have to use `test_apis` feature flag to use Aztec SRS indicates a problem in our API design. 

@zhenfeizhang I think we should make [this](https://github.com/EspressoSystems/cap/blob/a9489cff402408953bae25d4b27b5cdaa481f9dd/src/proof/mod.rs#L115) and [this](https://github.com/EspressoSystems/cap/blob/a9489cff402408953bae25d4b27b5cdaa481f9dd/src/proof/mod.rs#L123) `pub` and remove [this](https://github.com/EspressoSystems/cap/blob/1f4daf7368bdcbea501a96cdfb1219e5019f12c6/src/testing_apis.rs#L53). So that `reef` doesn't depend on test-apis feature flag.

File: src/traits.rs [hunk 3]
```diff
@@ -138,4 +139,5 @@ pub trait Ledger: Copy + Debug + Send + Sync {
     fn name() -> String;
     fn record_root_history() -> usize;
     fn merkle_height() -> u8;
+    fn crs() -> &'static UniversalParam;
```
Comment (alxiong) [inline src/traits.rs:142]: let's use srs instead for consistency.

File: Cargo.toml (hunk 2 above)
Comment (alxiong) [reply Cargo.toml:16]: hmm... actually giving another thought, @jbearer let's use [this api ](https://github.com/EspressoSystems/cap/blob/main/src/proof/mod.rs#L77) instead and avoid the `test_apis` flag.

Comment (jbearer) [reply Cargo.toml:16]: But then `reef` will only support BN254 curve? Is that okay? cc @tri-joe

Comment (alxiong) [reply Cargo.toml:16]: in case we want to make the changes: https://github.com/EspressoSystems/cap/pull/30

Comment (jbearer) [reply Cargo.toml]: Well the `cap` module of reef is a mock implementation that's only intended to be used for testing anyways. It's up to the actual products (CAPE and Espresso) to construct their production SRS in a secure way (which is why it's important to make `srs()` a trait function. Probably what I should actually do is guard the `cap` module with a `testing` feature flag.

Comment (zhenfeizhang) [reply Cargo.toml]: Ah... that makes sense to me. (did not realize that reef is for testing only)

Comment (jbearer) [reply Cargo.toml]: The trait definitions are for production but `cap` is just a simple test implementation of the traits so we can write tests for the traits

**Review by alxiong — APPROVED** [review]

**Review by tri-joe — APPROVED** [review]
LGTM

File: Cargo.toml (hunk 2 above)
Comment (tri-joe) [reply Cargo.toml]: cc @fkrell re: our discussion of BN254 vs BLS curves, especially https://github.com/EspressoSystems/espresso/issues/95 -- in short, the wallet code is now specifically using BN254 because of the existing SRS
